site_name: Semester Portfolio
site_description: Min læringsportfolio for AI, ML og Software Arkitektur

docs_dir: docs
site_dir: site
#trigger
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.footer

plugins:
  - roamlinks

nav:
  - Hjem: index.md
  - AI-ML:
      - AI-ML/index.md
      - AI-ML-forståelse:
          - AI-ML/AI-ML-forståelse/index.md
      - Projekter:
          - AI-ML/projekter/index.md
  - Software-arkitektur:
      - Software-arkitektur/index.md
  - Blog:
      - Blog/index.md
  - Generelt:
      - Generelt/index.md

