site_name: Semester Portfolio
site_description: Min l√¶ringsportfolio for AI, ML og Software Arkitektur

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top

plugins:
  - search

nav:
  - Forside: index.md

  - Blog:
      - AI & ML blog: "Blog/AI & ML blog/index.md"
      - Software Arkitektur blog: "Blog/Software arkitektur og Design pattern blogs blog/index.md"

  - Semester:
      - Velkomst: "Semester/Welcome.md"
      - AI & ML: "Semester/AI & ML/index.md"
      - Software Arkitektur & Design Patterns: "Semester/Software arkitektur og design pattern projekters/index.md"
      - Shared: "Semester/Shared/index.md"
